spring:
  #  main:
  #    log-startup-info: false

  datasource:
    url: jdbc:mysql://localhost:3306/airline_db
    username: root
    password :
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true